### ISSUE TITLE
post 관련 배치서버 개발

### ISSUE THREAD

**Issue by eerbse** [papaolabs/papao-server#46]
기존 실시간으로 open api 찌르는 방식의 문제점
- 페이징 어려움
- 데이터 관리 시 어려움이 있음 ( 상세 페이지 확인 등 )
- 시간이 너무 오래걸림 ( 조건에 따라 3초가 넘는 경우도 파다함 )

이를 위해 과거 데이터부터 현재 데이터까지 순차적으로 불러올 수 있도록 함
- 현재 데이터는 2008년부터 존재하는것 확인 ( 20080101~20081231 검색 기준, 이전년은 결과 없음 )
- 확인해본 결과 일 데이터는 1000건을 넘는 경우는 거의 없었음, 일반적으로 100~500건 사이
- 월 데이터의 경우 대체로 10000건 내외로 보임
- 월 데이터를 뽑는 경우 id 값이 유니크하지 않는 경우가 있어서 에러 발생함, 키를 자체적으로 가져갈 필요가 있음

* 우선 과거 데이터는 data set 을 얻어서 작업한다고 가정
* 배치는 30분 기준 우선 작업, 양은 매우 작을것으로 보이고 배치 작업 시마다 이미지에 대한 모델링까지 이루어져도 되는것으로 보임 (과거 데이터의 경우 생각해봐야함)

**Comment by eerbse** [comment]
spring batch
spring quartz

...
우선 Scheduler 통해서 간단히 구현해보도록 함

**Comment by eerbse** [comment]
현재 서버는 계속 단일 서버로 구성하고 다음 스프린트에서 분리시키도록 할 예정임

**Comment by eerbse** [comment]
배치는 30분 단위로 오늘 기준 전체 데이터를 계속 불러오면서 업데이트 치도록 함

**Comment by fractaliz2** [comment]
@bample  
- 배치 정책 참고
현재-한달 전 : 10분 배치
한달 전-6개월 전 : 일 배치
6개월 전-그 이전 : 임의 배치

* 한달 이라는 수치는 : 안락사까지의 기간인 10일에, 최대 3번까지 연장한 경우를 임의로 고려함.
